services:
  - type: web
    name: sentiment-analysis
    env: python
    buildCommand: "pip install -r requirements.txt && python download_nltk.py && python train_model.py"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
